spring:
  application:
    name: AwsCloudService

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
aws:
  region: ap-south-1
  access-key:
  secret-key:

server:
  port: 8080

