spring:
  application:
    name: AwsCloudService

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydatabase
aws:
  region: ap-south-1
  access-key: AKIAX5XSI5UT4M674AFL
  secret-key: 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

server:
  port: 8080

